server:
  port: ${PORT:8080}

spring:
  application:
    name: catalog-java-os

opensearch:
  endpoint: ${RETAIL_CATALOG_OPENSEARCH_ENDPOINT:localhost:9200}
  username: ${RETAIL_CATALOG_OPENSEARCH_USERNAME:admin}
  password: ${RETAIL_CATALOG_OPENSEARCH_PASSWORD:Catalog#3695}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always